// SPDX-FileCopyrightText: 2026 UltimateCalendar contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package com.qtekfun.ultimatecalendar.data.source

import com.qtekfun.ultimatecalendar.domain.model.EventInstance
import com.qtekfun.ultimatecalendar.domain.model.TimeRange
import com.qtekfun.ultimatecalendar.domain.recurrence.EventSeries
import com.qtekfun.ultimatecalendar.domain.recurrence.Expansion
import com.qtekfun.ultimatecalendar.domain.recurrence.OccurrenceKey
import com.qtekfun.ultimatecalendar.domain.recurrence.RecurrenceEngine
import com.qtekfun.ultimatecalendar.domain.recurrence.SeriesInstances
import com.qtekfun.ultimatecalendar.domain.recurrence.key
import java.time.Duration
import java.time.ZoneOffset

/**
 * Expands a stored series with the `RecurrenceEngine`, the way every source that keeps series in
 * Room does (CalDAV and the subscriptions), so that both show repetitions exactly alike.
 */
internal object SeriesExpander {
    private val PROBE: Duration = Duration.ofSeconds(1)

    /**
     * The instances of [series] in [range]. A rule the engine cannot read shows the series'
     * first occurrence only, rather than hiding the event.
     */
    fun expand(series: EventSeries, range: TimeRange): List<EventInstance> =
        when (val expansion = RecurrenceEngine.expand(series, range, ZoneOffset.UTC)) {
            is Expansion.Complete -> expansion.instances

            is Expansion.LimitReached -> expansion.instances

            is Expansion.Unsupported ->
                SeriesInstances.assemble(series, listOf(series.event.time), range, ZoneOffset.UTC)
        }

    fun occursIn(series: EventSeries, range: TimeRange) = expand(series, range).isNotEmpty()

    /** Whether [key] is an occurrence of [series]: generated by the rule, or already changed. */
    fun hasOccurrence(series: EventSeries, key: OccurrenceKey): Boolean {
        if (series.overrides.any { it.recurrenceId == key }) return true
        val start = when (key) {
            is OccurrenceKey.Moment -> key.at
            is OccurrenceKey.Day -> key.date.atStartOfDay(ZoneOffset.UTC).toInstant()
        }
        val probe = TimeRange(start, start.plus(PROBE))
        return expand(series, probe).any { it.time.key() == key }
    }
}
